version: '3.9'
services:

  postgres_exporter:
    container_name: postgres_exporter
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://root:root@postgres_container:5432/cbmoron_database?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - principal_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9091:9090"
    networks:
      - principal_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - principal_network
    depends_on:
      - prometheus
networks:
  principal_network:
    external: true